### ISSUE TITLE
还能用么？

### ISSUE THREAD

**Issue by xtlx2000** [ManiacMike/gorobot#11]
<error><ret>1203</ret><message>为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。Windows微信下载地址：https://pc.weixin.qq.com  Mac微信下载地址：https://mac.weixin.qq.com</message></error>

**Comment by xtlx2000** [comment]
登录时候提示这个啊？

**Comment by ManiacMike** [comment]
网页版登陆只能老微信号，你这个号用官方的wx.qq.com也用不了
