### ISSUE TITLE
“进行同步线路测试”失败，报错110x

### ISSUE THREAD

**Issue by athurg** [ManiacMike/gorobot#3]
webpush.weixin.qq.com 返回 1100
webpush2.weixin.qq.com 返回 1102
webpush.wechat.com 返回 1100
webpush1.wechat.com 返回 1100
webpush2.wechat.com 返回 1100
webpush1.wechatapp.com 返回 9999

**Comment by qida** [comment]
[*] 微信网页版 ... 开动
[*] 正在获取 uuid ... 成功,用时2.29324秒
[*] 正在获取 二维码 ... 成功,用时0.11143秒
please open on web broswer ip:8889/qrcode
[*] 请使用微信扫描二维码以登录 ...
[*] 请在手机上点击确认以登录 ...
[*] 正在登录 ... 成功,用时2.25490秒
[*] 微信初始化 ... 成功,用时0.28552秒
[*] 开启状态通知 ... 成功,用时0.07004秒
[*] 进行同步线路测试 ... 失败
[*] 退出程序

**Comment by ManiacMike** [comment]
不好意思最近在忙，wx换了api的域名，现在已修复
